### PR TITLE
Adds .md file for viewing on github

### PR DESCRIPTION
**Pull request by christopheralex**
Adds .md file .

### CODE REVIEW

**Comment by christopheralex** [comment]
Solves #59 temporarily.

**Comment by harryyikhchan** [comment]
found that the cross citation will not be working if we output github document as well. See if you all are ok with this. I have no opinion as long as we have a final report
image

**Comment by christopheralex** [comment]
Let me just add the .md file then for now.

**Comment by christopheralex** [comment]
I have removed all other edits and added only .md file for better view-ability until we add github pages to view our HTML.

**Comment by harryyikhchan** [comment]
Looks good

**Pull request merged**
