### PR TITLE
Adds an initial docker file 

### PR DESCRIPTION
**Pull request by christopheralex**
There is some issues with plot saving . Which is going to be the work ahead.

### CODE REVIEW

**Comment by christopheralex** [comment]
Solves #70 . Update base image as `datasciece-notebook`

**Comment by christopheralex** [comment]
Usage - 
1. docker build --tag cmp .
2. docker run --rm -it -v $(pwd):/home/jovyan/work/contraceptive cmp make -C /home/jovyan/work/contraceptive all

**Comment by harryyikhchan** [comment]
Reviewing. Please don't merge the PR

**Comment by harryyikhchan** [comment]
I can run it without any errors.

**Comment by christopheralex** [comment]
Adds github actions main.yml

**Comment by harryyikhchan** [comment]
Approved

**Pull request merged**
